// Regenerates src/og/font-data.ts: the OG-card font, vendored as base64.
//
// Why vendored as base64-in-TypeScript: tsc copies only .ts -> .js into dist,
// and the Docker image COPYs only src + dist — a raw .ttf/.otf next to the
// source would not survive the build. Inlining the font as base64 in a .ts file
// makes it a normal module that compiles to dist/og/font-data.js with zero build
// or Dockerfile changes. The bytes are decoded once at import via Buffer.from.
//
// Font: Inter (rsms/inter v3.19), OFL-1.1 — license at docs/licenses/Inter-OFL.txt.
// Subset to Latin + Latin-Extended + Greek + Cyrillic + the punctuation/symbols an
// OG card uses, so post titles in those scripts render as real glyphs (satori
// vectorizes text to <path>, so rendering never depends on system fonts).
//
// Requires: python3 with fonttools. For byte-reproducible output, pin the
// fonttools version (a different release can emit slightly different subset
// bytes): `pip3 install "fonttools==4.60.2"`. Run from repo root:
//   node scripts/build-og-font.mjs
// The generated src/og/font-data.ts is committed, so this only needs re-running
// to change the font or its coverage.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const VERSION = 'v3.19';
const BASE = `https://github.com/rsms/inter/raw/${VERSION}/docs/font-files`;
const WEIGHTS = [
  { name: 'regular', file: 'Inter-Regular.otf' },
  { name: 'bold', file: 'Inter-Bold.otf' },
];

// Keep coverage broad enough for European + Cyrillic + Greek post titles while
// dropping CJK/emoji/rare blocks that would bloat the vendored bytes.
const UNICODES = [
  'U+0020-00FF', // Basic Latin + Latin-1 Supplement
  'U+0100-017F', // Latin Extended-A
  'U+0180-024F', // Latin Extended-B
  'U+0300-036F', // Combining Diacritical Marks
  'U+0370-03FF', // Greek
  'U+0400-04FF', // Cyrillic
  'U+0500-052F', // Cyrillic Supplement
  'U+2000-206F', // General Punctuation (– — ' ' " " • … ‰)
  'U+20A0-20BF', // Currency symbols (€ …)
  'U+2122', // ™
  'U+2190-2193', // arrows ← ↑ → ↓
  'U+2212', // minus −
  'U+2022', // bullet •
  'U+2026', // ellipsis …
  'U+25A0-25CF', // geometric shapes (bullets/markers)
].join(',');
const FEATURES = 'kern,locl,ccmp,mark,mkmk';

const work = mkdtempSync(join(tmpdir(), 'kiko-og-font-'));
const encoded = {};

for (const w of WEIGHTS) {
  const src = join(work, w.file);
  const out = join(work, `${w.name}-subset.otf`);
  const res = await fetch(`${BASE}/${w.file}`);
  if (!res.ok) throw new Error(`download failed for ${w.file}: ${res.status}`);
  writeFileSync(src, Buffer.from(await res.arrayBuffer()));
  execFileSync(
    'python3',
    [
      '-m',
      'fontTools.subset',
      src,
      `--unicodes=${UNICODES}`,
      `--layout-features=${FEATURES}`,
      '--no-hinting',
      '--notdef-outline',
      '--name-IDs=*',
      `--output-file=${out}`,
    ],
    { stdio: ['ignore', 'ignore', 'inherit'] },
  );
  encoded[w.name] = readFileSync(out).toString('base64');
  console.log(`${w.name}: ${readFileSync(out).length} bytes -> ${encoded[w.name].length} base64 chars`);
}

const header = `// GENERATED by scripts/build-og-font.mjs — do not edit by hand.
// Inter ${VERSION} (rsms/inter), OFL-1.1; subset for OG cards. See docs/licenses/Inter-OFL.txt.
// Excluded from prettier (.prettierignore) and eslint (eslint.config.js) — it is a vendored asset.
/* eslint-disable */
`;
const body =
  `const REGULAR_BASE64 =\n  '${encoded.regular}';\n\n` +
  `const BOLD_BASE64 =\n  '${encoded.bold}';\n\n` +
  `/** Inter Regular (400), subset OTF — decoded once at import. */\n` +
  `export const interRegular: Buffer = Buffer.from(REGULAR_BASE64, 'base64');\n\n` +
  `/** Inter Bold (700), subset OTF — decoded once at import. */\n` +
  `export const interBold: Buffer = Buffer.from(BOLD_BASE64, 'base64');\n`;

const target = fileURLToPath(new URL('../src/og/font-data.ts', import.meta.url));
writeFileSync(target, header + '\n' + body);
console.log(`wrote ${target}`);
